# Generated by Django 5.2.3 on 2025-06-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.RemoveField(
            model_name='class',
            name='name',
        ),
        migrations.AddField(
            model_name='class',
            name='batch',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='class',
            name='course',
            field=models.CharField(choices=[('BCA-AI', 'BCA (Artificial Intelligence)'), ('BBA-AV', 'BBA with Aviation'), ('BCOM-CO', 'B.Com. Model I Co-operation'), ('BCOM-FT', 'B.Com. Model I Finance & Taxation'), ('BSC-ECT', 'B.Sc. Electronics with Computer Technology (Honours)'), ('BSC-BT', 'B.Sc. Biotechnology'), ('BA-ENG', 'B.A. English Literature & Communication Studies Model III'), ('BSW', 'Bachelor of Social Work'), ('MSC-CS', 'M.Sc. Computer Science'), ('MA-HRM', 'MA Human Resource Management'), ('MCOM-FT', 'M.Com. Finance & Taxation'), ('MSC-ELX', 'M.Sc. Electronics'), ('MSC-BT', 'M.Sc. Biotechnology'), ('MA-ENG', 'M.A. English Literature')], default='A', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='level',
            field=models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], default='UG', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='year',
            field=models.CharField(default='1st', max_length=3),
            preserve_default=False,
        ),
    ]
