# Generated by Django 5.2.3 on 2025-06-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_class_options_remove_class_name_class_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='course',
            field=models.CharField(choices=[('BCA-AI', 'BCA (Artificial Intelligence)'), ('BBA-AV', 'BBA with Aviation'), ('BCOM-CO', 'B.Com. Model I Co-operation'), ('BCOM-FT', 'B.Com. Model I Finance & Taxation'), ('BSC-ECT', 'B.Sc. Electronics with Computer Technology (Honours)'), ('BSC-BT', 'B.Sc. Biotechnology'), ('BA-ENG', 'B.A. English Literature & Communication Studies Model III'), ('BSW', 'Bachelor of Social Work'), ('MSC-CS', 'M.Sc. Computer Science'), ('MA-HRM', 'MA Human Resource Management'), ('MCOM-FT', 'M.Com. Finance & Taxation'), ('MSC-ELX', 'M.Sc. Electronics'), ('MSC-BT', 'M.Sc. Biotechnology'), ('MA-ENG', 'M.A. English Literature')], default='BCA-AI', max_length=20),
        ),
        migrations.AlterField(
            model_name='class',
            name='level',
            field=models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], default='UG', max_length=2),
        ),
        migrations.AlterField(
            model_name='class',
            name='year',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd')], default='1st', max_length=3),
        ),
    ]
